# This workflow will do a clean install of node dependencies, build the source code and run tests across different platforms

name: build

on:
  push:
    branches-ignore:
      - 'releases/**/*'
    paths:
    - 'src/**/*'
    - 'README.md'
    - '.github/workflows/build.yml'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [ 10.x ]
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint code
      run: npm run lint
    - name: Build, test (Linux-only)
      run: xvfb-run -a npm test
      if: runner.os == 'Linux'
    - name: Build, test
      run: npm test
      if: runner.os != 'Linux'
